# Technology Stack - Material Law
# Defines approved libraries, frameworks, and dependencies

version: "1.0.0"
last_updated: "2025-12-03"

# Python version requirements
python:
  minimum_version: "3.9"
  recommended_version: "3.11"
  maximum_version: "3.12"

# Core dependencies - Always allowed
core_dependencies:
  - name: "python-stdlib"
    description: "Python standard library modules"
    always_allowed: true
    
# Approved third-party libraries
approved_libraries:
  # Data processing and validation
  - name: "pyyaml"
    purpose: "YAML parsing and serialization"
    min_version: "6.0"
    max_version: "6.x"
    import_patterns:
      - "yaml"
    security_notes: "Use safe_load() instead of load()"
    
  - name: "jsonschema"
    purpose: "JSON Schema validation"
    min_version: "4.0"
    max_version: "4.x"
    import_patterns:
      - "jsonschema"
      - "jsonschema.validators"
    
  # Code analysis
  - name: "ast"
    purpose: "Abstract Syntax Tree parsing (stdlib)"
    builtin: true
    import_patterns:
      - "ast"
      
  # Testing frameworks
  - name: "pytest"
    purpose: "Testing framework"
    min_version: "7.0"
    scope: "dev"
    import_patterns:
      - "pytest"
      
  - name: "pytest-cov"
    purpose: "Coverage reporting"
    min_version: "4.0"
    scope: "dev"
    import_patterns:
      - "pytest_cov"
      
  # Code quality tools
  - name: "ruff"
    purpose: "Linting and formatting"
    min_version: "0.1.0"
    scope: "dev"
    
  - name: "mypy"
    purpose: "Static type checking"
    min_version: "1.0"
    scope: "dev"
    import_patterns:
      - "mypy"

  # File and path handling
  - name: "pathlib"
    purpose: "Object-oriented filesystem paths (stdlib)"
    builtin: true
    import_patterns:
      - "pathlib"
      
  # Logging and debugging
  - name: "logging"
    purpose: "Logging facility (stdlib)"
    builtin: true
    import_patterns:
      - "logging"

# Explicitly forbidden libraries
forbidden_libraries:
  - name: "pickle"
    reason: "Security risk - arbitrary code execution"
    alternatives: ["json", "yaml"]
    
  - name: "eval"
    reason: "Security risk - arbitrary code execution"
    alternatives: ["ast.literal_eval"]
    
  - name: "exec"
    reason: "Security risk - arbitrary code execution"
    alternatives: ["Use importlib for dynamic imports"]
    
  - name: "os.system"
    reason: "Security risk - shell injection"
    alternatives: ["subprocess with shell=False"]

# Import rules and patterns
import_rules:
  # Standard library imports that are always allowed
  stdlib_allowed:
    - "os"
    - "sys"
    - "re"
    - "json"
    - "typing"
    - "pathlib"
    - "logging"
    - "ast"
    - "argparse"
    - "collections"
    - "itertools"
    - "functools"
    - "dataclasses"
    - "enum"
    
  # Import style requirements
  style:
    - rule: "Use absolute imports for project modules"
      example: "from validators.common import parser"
      
    - rule: "Group imports: stdlib, third-party, local"
      example: |
        # Standard library
        import os
        import sys
        
        # Third-party
        import yaml
        
        # Local
        from validators import common
        
    - rule: "Avoid wildcard imports"
      forbidden: "from module import *"
      
    - rule: "Use specific imports when possible"
      preferred: "from pathlib import Path"
      discouraged: "import pathlib"

# Dependency management
dependency_management:
  tool: "pip"
  requirements_file: "requirements.txt"
  dev_requirements_file: "requirements-dev.txt"
  
  versioning_policy:
    - "Pin exact versions in requirements.txt for reproducibility"
    - "Use compatible release (~=) or minimum version (>=) in setup.py"
    - "Document reason for any version pins"
    
  update_policy:
    - "Review security advisories monthly"
    - "Update dependencies quarterly unless security issue"
    - "Test all updates in CI before merging"

# Platform and environment
platform:
  supported_os:
    - "Linux"
    - "macOS"
    - "Windows"
    
  container:
    base_image: "python:3.11-slim"
    package_manager: "pip"

# Security policies
security:
  scan_dependencies:
    enabled: true
    tools:
      - "safety"
      - "bandit"
      
  code_analysis:
    enabled: true
    tools:
      - "ruff"
      - "mypy"
      
  allowed_network_calls:
    - description: "No network calls from validators"
      enforcement: "strict"
      exceptions: []

# Validation configuration
validation:
  strict_mode: true
  fail_on_warning: false
  report_format: "human"  # Options: human, json, junit
  
# Extension points
extensions:
  custom_validators:
    enabled: true
    location: "validators/custom/"
    requirements:
      - "Must inherit from BaseValidator"
      - "Must be registered in validators/__init__.py"
      - "Must include tests"
